# Generated by Django 5.1.7 on 2025-04-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Movie_id', models.CharField(help_text="Like 'm101.m102..'", max_length=20)),
                ('Title', models.CharField(max_length=100)),
                ('Release_year', models.IntegerField()),
                ('Genre', models.CharField(max_length=30)),
                ('Rating', models.FloatField(help_text="From '0.0' to '5.0'")),
            ],
        ),
    ]
